server:
  port: 8080
spring:
  datasource:
    tasks:
      url: jdbc:postgresql://localhost/taskmanagertasks
      jdbc-url: jdbc:postgresql://localhost/taskmanagertasks
      username: someuser
      password: somepassword
      driver-class-name: org.postgresql.Driver

  profiles:
    active: console-and-file-logging


jwt:
  issuer: 'devilprime5@gmail.com'
  signingKey: '10414d3bf71b47bbf7566f4d59baae929c0b869a01079cb5dd72d6a3aae5dc6924dd049564f1f9989e2eed5ba92d30cde2216b2e5f9982538c831c81d77511fc'
  aTokenDuration: 10

logging:
  path: logs
  level:
    root: INFO
    it.sevenbits.taskmanager: DEBUG